<?php
/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>

<?php if ($block->getCustomerAccountManagerDetails()) : ?>
    <p>
        <strong>
            <?= $block->escapeHtml(__('Account Manager')) ?>
        </strong>
    </p>
    <p>
        <?= $block->escapeHtml(__('Name: %1', $block->getAccountManagerName())) ?><br>
        <?= $block->escapeHtml(__('Email: %1', $block->getAccountManagerEmail())) ?><br>
    </p>
<?php endif; ?>
